In [1]:
import pandas as pd

In [2]:
words = pd.read_csv("data/words_20000_clean.csv", index_col=0)
chars = words.iloc[:, 1:6]  # Get just the character columns
chars.head()

      char0 char1 char2 char3 char4
444       s     a     l     e     s
10382     c     a     r     e     s
17605     c     o     r     e     s
8097      s     a     v     e     s
9954      f     a     r     e     s

In [3]:
# Get the frequency of each letter in that spot of the 5 spots 
freqs = pd.DataFrame()

char0 = chars['char0'].value_counts(normalize=True)
for char, freq in char0.iteritems():
    freqs.loc[char, 'char0'] = freq

char1 = chars['char1'].value_counts(normalize=True)
for char, freq in char1.iteritems():
    freqs.loc[char, 'char1'] = freq

char2 = chars['char2'].value_counts(normalize=True)
for char, freq in char2.iteritems():
    freqs.loc[char, 'char2'] = freq

char3 = chars['char3'].value_counts(normalize=True)
for char, freq in char3.iteritems():
    freqs.loc[char, 'char3'] = freq

char4 = chars['char4'].value_counts(normalize=True)
for char, freq in char0.iteritems():
    freqs.loc[char, 'char4'] = freq

freqs = freqs.sort_index()  # Sort the index a-z
freqs

      char0     char1     char2     char3     char4
a  0.058366  0.166926  0.119455  0.068872  0.058366
b  0.072763  0.005058  0.021790  0.016342  0.072763
c  0.083268  0.014008  0.030739  0.050973  0.083268
d  0.050973  0.008949  0.031907  0.040856  0.050973
e  0.029572  0.127626  0.071595  0.172374  0.029572
f  0.054475  0.001556  0.007004  0.008560  0.054475
g  0.035409  0.003891  0.030350  0.026070  0.035409
h  0.037354  0.050195  0.005058  0.012062  0.037354
i  0.016342  0.111284  0.097276  0.069650  0.016342
j  0.016732       NaN  0.001556  0.000778  0.016732
k  0.016732  0.003113  0.010506  0.033852  0.016732
l  0.047471  0.069261  0.064202  0.062257  0.047471
m  0.056031  0.009728  0.031518  0.028794  0.056031
n  0.021790  0.023735  0.086381  0.080934  0.021790
o  0.016342  0.148638  0.081323  0.055642  0.016342
p  0.061089  0.019066  0.021012  0.021401  0.061089
q  0.007393  0.001556       NaN  0.001167  0.007393
r  0.048638  0.090661  0.087549  0.064202  0.048638
s  0.124125  0.013230  0.041634  0.050584  0.124125
t  0.068093  0.027237  0.057977  0.074708  0.068093
u  0.009339  0.065759  0.043191  0.026848  0.009339
v  0.021012  0.005058  0.021012  0.012451  0.021012
w  0.036965  0.012451  0.009339  0.008949  0.036965
x  0.001946  0.004280  0.011284  0.001946  0.001946
y  0.005058  0.015564  0.012062  0.005447  0.005058
z  0.002724  0.001167  0.004280  0.004280  0.002724

In [4]:
# Save the above data to a lookup table for use in Wordle solver
freqs.to_csv("data/lookup_char-freqs.csv")

In [5]:
# Visualize the data (color coding doesn't show up on GitHub, fyi)
f = '{:.1f}' + ' %'
freqs_percs = freqs*100
freqs_styled = freqs_percs.style.apply(lambda x: ["background: red" if v == max(x) else "" for v in x], axis=0).format(f)
freqs_styled